INSERT INTO code_master (id, code_name, code_value, created_by, created_at, updated_by, updated_at, version)
VALUES ('550e8400-e29b-41d4-a716-446655440204', 'DOCUMENT_TYPES',
        '{"IDENTITY": {"name": "Identity Document", "description": "Government issued identity document", "active": true}, "ADDRESS_PROOF": {"name": "Address Proof", "description": "Proof of residential address", "active": true}, "INCOME_PROOF": {"name": "Income Proof", "description": "Salary certificate or income statement", "active": true}, "BANK_STATEMENT": {"name": "Bank Statement", "description": "Bank account statement", "active": true}, "PAN_CARD": {"name": "PAN Card", "description": "Permanent Account Number card", "active": true}, "AADHAR_CARD": {"name": "Aadhar Card", "description": "Aadhar identification card", "active": true}, "PASSPORT": {"name": "Passport", "description": "International passport", "active": true}, "DRIVING_LICENSE": {"name": "Driving License", "description": "Valid driving license", "active": true}, "VOTER_ID": {"name": "Voter ID", "description": "Voter identification card", "active": true}, "UTILITY_BILL": {"name": "Utility Bill", "description": "Electricity, water, or gas bill", "active": true}, "RENT_AGREEMENT": {"name": "Rent Agreement", "description": "Rental agreement document", "active": true}, "PROPERTY_DOCUMENT": {"name": "Property Document", "description": "Property ownership or lease document", "active": true}, "EMPLOYMENT_CERTIFICATE": {"name": "Employment Certificate", "description": "Employment verification certificate", "active": true}, "SALARY_SLIP": {"name": "Salary Slip", "description": "Monthly salary slip", "active": true}, "FORM_16": {"name": "Form 16", "description": "Tax deduction certificate", "active": true}, "ITR": {"name": "Income Tax Return", "description": "Income tax return document", "active": true}, "BALANCE_SHEET": {"name": "Balance Sheet", "description": "Financial balance sheet", "active": true}, "P_L_STATEMENT": {"name": "P&L Statement", "description": "Profit and loss statement", "active": true}, "AUDIT_REPORT": {"name": "Audit Report", "description": "Audited financial report", "active": true}, "OTHER": {"name": "Other", "description": "Other document type", "active": true}}',
        'system', '2025-09-26 05:35:00.000', '', '2025-09-26 05:35:00.000', 0),
       ('550e8400-e29b-41d4-a716-446655440205', 'DOCUMENT_CATEGORIES',
        '{"IDENTITY_VERIFICATION": {"name": "Identity Verification", "description": "Documents for identity verification", "active": true}, "ADDRESS_VERIFICATION": {"name": "Address Verification", "description": "Documents for address verification", "active": true}, "INCOME_VERIFICATION": {"name": "Income Verification", "description": "Documents for income verification", "active": true}, "EMPLOYMENT_VERIFICATION": {"name": "Employment Verification", "description": "Documents for employment verification", "active": true}, "FINANCIAL_VERIFICATION": {"name": "Financial Verification", "description": "Documents for financial verification", "active": true}, "PROPERTY_VERIFICATION": {"name": "Property Verification", "description": "Documents for property verification", "active": true}, "KYC_DOCUMENTS": {"name": "KYC Documents", "description": "Know Your Customer documents", "active": true}, "LOAN_APPLICATION": {"name": "Loan Application", "description": "Loan application related documents", "active": true}, "COLLATERAL_DOCUMENTS": {"name": "Collateral Documents", "description": "Documents related to collateral", "active": true}, "LEGAL_DOCUMENTS": {"name": "Legal Documents", "description": "Legal and compliance documents", "active": true}, "INSURANCE_DOCUMENTS": {"name": "Insurance Documents", "description": "Insurance related documents", "active": true}, "TAX_DOCUMENTS": {"name": "Tax Documents", "description": "Tax related documents", "active": true}, "OTHER": {"name": "Other", "description": "Other document category", "active": true}}',
        'system', '2025-09-26 05:35:00.000', '', '2025-09-26 05:35:00.000', 0),
       ('550e8400-e29b-41d4-a716-446655440206', 'TASK_STATUS',
        '{"PENDING": {"name": "Pending", "description": "Task is pending", "active": true}, "IN_PROGRESS": {"name": "In Progress", "description": "Task is in progress", "active": true}, "COMPLETED": {"name": "Completed", "description": "Task is completed", "active": true}, "CANCELLED": {"name": "Cancelled", "description": "Task is cancelled", "active": true}, "ON_HOLD": {"name": "On Hold", "description": "Task is on hold", "active": true}, "OVERDUE": {"name": "Overdue", "description": "Task is overdue", "active": true}}',
        'system', '2025-09-26 05:35:00.000', '', '2025-09-26 05:35:00.000', 0),
       ('550e8400-e29b-41d4-a716-446655440207', 'LEAD_STATUS',
        '{"NEW": {"name": "New", "description": "New lead", "active": true}, "CONTACTED": {"name": "Contacted", "description": "Lead has been contacted", "active": true}, "QUALIFIED": {"name": "Qualified", "description": "Lead is qualified", "active": true}, "PROPOSAL_SENT": {"name": "Proposal Sent", "description": "Proposal has been sent", "active": true}, "NEGOTIATION": {"name": "Negotiation", "description": "In negotiation phase", "active": true}, "APPROVED": {"name": "Approved", "description": "Lead is approved", "active": true}, "REJECTED": {"name": "Rejected", "description": "Lead is rejected", "active": true}, "CONVERTED": {"name": "Converted", "description": "Lead converted to customer", "active": true}, "LOST": {"name": "Lost", "description": "Lead is lost", "active": true}, "ON_HOLD": {"name": "On Hold", "description": "Lead is on hold", "active": true}}',
        'system', '2025-09-26 05:35:00.000', '', '2025-09-26 05:35:00.000', 0);
