INSERT INTO master_code (parent_id,
                         key,
                         name,
                         description,
                         is_system_defined,
                         created_by,
                         created_at,
                         version)
VALUES (NULL,
        'DOCUMENT_MASTER',
        '{"default": "Document Master"}',
        '{"default": "Document Tags will one parent using this"}',
        TRUE,
        'system',
        '2025-01-27 10:00:00',
        0);
