rootProject.name = "navigator"

include("main")
include("common")
include("webhooks")
include("redash")

include(":features:creditbureau")
include(":features:consent")
include(":features:advisor")
include(":features:person")
include(":features:usermanagement")
include("features:master")
include("features:address")
include("features:lead")
include("features:lender")
include("features:document")
include("features:offices")
include("features:leadpersons")
include("features:notes")
include("features:rolemanagement")
include("features:notifications")
include("features:marketing")
include("features:workflow")
include("features:stage")
include("features:task")
include("features:staff")
include("integrations")
include("features:call")
include("features:identifier")
include("features:campaign")
include("features:bulk-operations")
include("externals:exotel")
include("externals:whatsapp")
include("externals:creditbureau")
include("features:referral")

