rootProject.name = "navigator"

include("main")
include("common")
include(":features:creditbureau")
include(":features:advisor")
include(":features:advisorleadmapping")
include(":features:person")
include("features:master")
include("features:address")
include("features:lead")
include("features:payment")
include("features:document")
include("features:identifiers")
include("features:applicant")
include("features:income")
include("features:taskdefinitions")
include("features:tasks")
include("features:pipelines")
include("features:stages")