rootProject.name = "navigator"

include("main")
include("common")
include("security")
include(":features:creditbureau")
include(":features:advisor")
include(":features:person")
include("features:master")
include("features:address")
include("features:lead")
include("features:lender")
include("features:document")
include("features:offices")
include("features:identifiers")
include("features:leadpersons")
include("features:tasks")
include("features:pipelines")
include("features:notes")
include("features:rolemanagement")
include("security")
