package com.nivasafinance.features.master.codemaster

object SystemControlledMasterCodes {
    const val DOCUMENT_MASTER = "DOCUMENT_MASTER"
    const val LENDER_STAGE_MASTER = "LENDER_STAGE_MASTER"
    const val LENDER_REJECTION_REASON_MASTER = "LENDER_REJECTION_REASON_MASTER"
    const val LEAD_REJECT_REASON_MASTER = "LEAD_REJECT_MASTER"
    const val LEAD_WITHDRAWAL_REASON_MASTER = "LEAD_WITHDRAWAL_REASON_MASTER"
    const val LEAD_ONHOLD_REASON_MASTER = "LEAD_ONHOLD_REASON_MASTER"
}
