package com.nivasafinance.features.master.codemaster

object SystemControlledMasterCodes {
    const val LEAD_DOCUMENT_MASTER = "LEAD_DOCUMENT_MASTER"
    const val LENDER_STAGE_MASTER = "LENDER_STAGE_MASTER"
    const val LENDER_REJECTION_REASON_MASTER = "LENDER_REJECTION_REASON_MASTER"
    const val LEAD_REJECT_REASON_MASTER = "LEAD_REJECT_REASON_MASTER"
    const val LEAD_WITHDRAWAL_REASON_MASTER = "LEAD_WITHDRAWAL_REASON_MASTER"
    const val LEAD_ONHOLD_REASON_MASTER = "LEAD_ONHOLD_REASON_MASTER"
    
    // Credit Profile Masters
    const val LEAD_OCCUPATION_PROFILE_MASTER = "LEAD_OCCUPATION_PROFILE_MASTER"
    const val LEAD_ROOF_PROFILE_MASTER = "LEAD_ROOF_PROFILE_MASTER"
    const val LEAD_LTV_MASTER = "LEAD_LTV_MASTER"
    const val LEAD_FOIR_MASTER = "LEAD_FOIR_MASTER"
    const val LEAD_MONTHLY_INCOME_MASTER = "LEAD_MONTHLY_INCOME_MASTER"
    const val LEAD_PROPERTY_DOCUMENT_TYPE_MASTER = "LEAD_PROPERTY_DOCUMENT_TYPE_MASTER"
    const val LEAD_LOCATION_MASTER = "LEAD_LOCATION_MASTER"
    const val LEAD_BUREAU_RATING_MASTER = "LEAD_BUREAU_RATING_MASTER"
    const val LEAD_CUSTOMER_PROFILE_MASTER = "LEAD_CUSTOMER_PROFILE_MASTER"

    // Marketing Sourcing
    const val MARKETING_SOURCE_MASTER = "MARKETING_SOURCE_MASTER"
    const val MARKETING_CHANNEL_MASTER = "MARKETING_CHANNEL_MASTER"
}
