package com.nivasafinance.common.events;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Enumerates business events published by the platform.
 */
@Getter
@RequiredArgsConstructor
public enum BusinessEvent {

    /**
     * Raised when a new lead is created in the system.
     */
    LEAD_CREATED("LEAD_CREATED"),
    LEAD_UPDATED("LEAD_UPDATED"),
    LEAD_REJECTED("LEAD_REJECTED"),
    LEAD_WITHDRAWN("LEAD_WITHDRAWN"),
    LEAD_ON_HOLD("LEAD_ON_HOLD"),
    LEAD_RESUMED("LEAD_RESUMED"),
    LEAD_COMPLETED("LEAD_COMPLETED"),
    LEAD_DROPOFF("LEAD_DROPOFF"),
    LEAD_CALL_LOG_CREATED("LEAD_CALL_LOG_CREATED"),
    LEAD_LENDER_CREATED("LEAD_LENDER_CREATED"),
    LEAD_LENDER_UPDATED("LEAD_LENDER_UPDATED"),
    LEAD_LENDER_REJECTED("LEAD_LENDER_REJECTED"),
    LEAD_LENDER_SUBMITTED("LEAD_LENDER_SUBMITTED"),
    LEAD_DOCUMENT_CREATED("LEAD_DOCUMENT_CREATED"),
    LEAD_DOCUMENT_UPDATED("LEAD_DOCUMENT_UPDATED"),
    LEAD_DOCUMENT_DELETED("LEAD_DOCUMENT_DELETED"),
    LEAD_NOTE_CREATED("LEAD_NOTE_CREATED"),
    LEAD_NOTE_UPDATED("LEAD_NOTE_UPDATED"),
    LEAD_NOTE_DELETED("LEAD_NOTE_DELETED"),
    LEAD_CONTACT_CREATED("LEAD_CONTACT_CREATED"),
    LEAD_CONTACT_UPDATED("LEAD_CONTACT_UPDATED"),
    LEAD_CONTACT_DELETED("LEAD_CONTACT_DELETED"),
    ADVISOR_CREATED("ADVISOR_CREATED"),
    ADVISOR_UPDATED("ADVISOR_UPDATED"),
    ADVISOR_REJECTED("ADVISOR_REJECTED"),
    ADVISOR_DORMANT("ADVISOR_DORMANT"),
    ADVISOR_ACTIVE("ADVISOR_ACTIVE"),
    ADVISOR_OUT_OF_GEO("ADVISOR_OUT_OF_GEO"),
    ADVISOR_NOTE_CREATED("ADVISOR_NOTE_CREATED"),
    ADVISOR_NOTE_UPDATED("ADVISOR_NOTE_UPDATED"),
    ADVISOR_NOTE_DELETED("ADVISOR_NOTE_DELETED"),
    ADVISOR_CALL_LOG_CREATED("ADVISOR_CALL_LOG_CREATED"),
    STAGE_TRANSITIONED("STAGE_TRANSITIONED"),
    ;

    private final String code;

    @Override
    public String toString() {
        return code;
    }
}


