spring.messages.encoding=UTF-8
spring.datasource.url=jdbc:postgresql://localhost:5432/navigator-platform
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml