package com.nivasafinance.features.document.controller

import com.nivasafinance.features.document.config.DocumentStorageProperties
import com.nivasafinance.features.document.dto.DocumentRequest
import com.nivasafinance.features.document.dto.DocumentResponse
import com.nivasafinance.features.document.dto.DocumentVerificationRequest
import com.nivasafinance.features.document.exception.DocumentExceptionFactory
import com.nivasafinance.features.document.service.DocumentService
import jakarta.servlet.http.HttpServletResponse
import org.springframework.beans.factory.annotation.Value
import org.springframework.context.MessageSource
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.DeleteMapping
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.PutMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.multipart.MultipartFile
import java.io.IOException
import java.util.UUID

@RestController
@RequestMapping("/api/documents")
class DocumentController(
    private val documentService: DocumentService,
    private val documentStorageProperties: DocumentStorageProperties,
    private val messageSource: MessageSource
) {

    companion object {
        private const val DEFAULT_EXPIRATION_SECONDS = 300L // 5 minutes
    }

    private val documentExceptionFactory = DocumentExceptionFactory(messageSource)

    @Value("\${document.storage.signed-url.expiration-seconds:300}")
    private val defaultExpirationSeconds: Long = DEFAULT_EXPIRATION_SECONDS

    @PostMapping(consumes = [MediaType.MULTIPART_FORM_DATA_VALUE])
    fun createDocument(
        @RequestParam("entityId") entityId: UUID,
        @RequestParam("entityType") entityType: String,
        @RequestParam("documentType") documentType: String,
        @RequestParam("tags") tags: List<String>? = null,
        @RequestParam("file") file: MultipartFile
    ): ResponseEntity<DocumentResponse> {
        val documentRequest = DocumentRequest(
            entityId = entityId,
            entityType = entityType,
            documentType = documentType,
            fileName = file.originalFilename ?: "unknown",
            fileType = file.contentType,
            fileSize = file.size,
            provider = documentStorageProperties.provider,
            storageKey = "", // Will be generated by service
            tags = tags
        )

        val document = documentService.createDocument(documentRequest, file.inputStream)
        return ResponseEntity.status(HttpStatus.CREATED).body(document)
    }

    @GetMapping("/entity/{entityType}/{entityId}")
    fun getDocumentsByEntityTypeAndEntityId(
        @PathVariable entityType: String,
        @PathVariable entityId: UUID
    ): ResponseEntity<List<DocumentResponse>> {
        val documents = documentService.getDocumentsByEntityTypeAndEntityId(entityType, entityId)
        return ResponseEntity.ok(documents)
    }

    @GetMapping("/{id}")
    fun getDocumentById(@PathVariable id: UUID): ResponseEntity<DocumentResponse> {
        val document = documentService.getDocumentById(id)
        return ResponseEntity.ok(document)
    }

    @PutMapping("/{entityType}/{entityId}/{documentId}")
    fun updateDocument(
        @PathVariable entityType: String,
        @PathVariable entityId: UUID,
        @PathVariable documentId: UUID,
        @RequestBody documentRequest: DocumentRequest
    ): ResponseEntity<DocumentResponse> {
        // Validate that the document belongs to the specified entity
        val document = documentService.getDocumentById(documentId)
        if (document.entityId != entityId || document.entityType != entityType) {
            throw documentExceptionFactory.createEntityNotFoundException(entityId, entityType)
        }

        val updatedDocument = documentService.updateDocument(documentId, documentRequest)
        return ResponseEntity.ok(updatedDocument)
    }

    @DeleteMapping("/{entityType}/{entityId}/{documentId}")
    fun deleteDocumentById(
        @PathVariable entityType: String,
        @PathVariable entityId: UUID,
        @PathVariable documentId: UUID
    ): ResponseEntity<Unit> {
        // Validate that the document belongs to the specified entity
        val document = documentService.getDocumentById(documentId)
        if (document.entityId != entityId || document.entityType != entityType) {
            throw documentExceptionFactory.createEntityNotFoundException(entityId, entityType)
        }

        documentService.deleteDocumentById(documentId)
        return ResponseEntity.noContent().build()
    }

    @GetMapping("/{entityType}/{entityId}/{documentId}/download")
    fun downloadFile(
        @PathVariable entityType: String,
        @PathVariable entityId: UUID,
        @PathVariable documentId: UUID,
        response: HttpServletResponse
    ) {
        // First get the document to check if it exists
        val document = documentService.getDocumentById(documentId)

        // Validate that the document belongs to the specified entity
        if (document.entityId != entityId || document.entityType != entityType) {
            throw documentExceptionFactory.createEntityNotFoundException(entityId, entityType)
        }

        // Only after validation do we proceed with the download
        val resource = documentService.downloadDocument(documentId)

        // Set response headers manually
        response.contentType = document.fileType ?: "application/octet-stream"
        response.setHeader("Content-Disposition", "attachment; filename=\"${document.fileName}\"")

        // Copy the resource to response output stream
        try {
            resource.inputStream.use { inputStream ->
                inputStream.copyTo(response.outputStream)
            }
        } catch (e: IOException) {
            throw documentExceptionFactory.createOperationException("write file to response", e)
        }
    }

    @GetMapping("/{entityType}/{entityId}/{documentId}/download-url")
    fun getDocumentDownloadUrl(
        @PathVariable entityType: String,
        @PathVariable entityId: UUID,
        @PathVariable documentId: UUID,
        @RequestParam(required = false) expiresIn: Long?
    ): ResponseEntity<Map<String, String>> {
        // Validate that the document belongs to the specified entity
        val document = documentService.getDocumentById(documentId)
        if (document.entityId != entityId || document.entityType != entityType) {
            throw documentExceptionFactory.createEntityNotFoundException(entityId, entityType)
        }

        val actualExpiresIn = expiresIn ?: defaultExpirationSeconds
        val downloadUrl = documentService.getDocumentDownloadUrl(documentId, actualExpiresIn)
        return ResponseEntity.ok(mapOf("downloadUrl" to downloadUrl))
    }

    @PutMapping("/{entityType}/{entityId}/{documentId}/verify")
    fun verifyDocument(
        @PathVariable entityType: String,
        @PathVariable entityId: UUID,
        @PathVariable documentId: UUID,
        @RequestBody verificationRequest: DocumentVerificationRequest
    ): ResponseEntity<DocumentResponse> {
        // Validate that the document belongs to the specified entity
        val document = documentService.getDocumentById(documentId)
        if (document.entityId != entityId || document.entityType != entityType) {
            throw documentExceptionFactory.createEntityNotFoundException(entityId, entityType)
        }

        val verifiedDocument = documentService.verifyDocument(documentId, verificationRequest)
        return ResponseEntity.ok(verifiedDocument)
    }
}
