package com.nivasafinance.features.rolemanagement.enums;

public enum OperationsEnum {
    READ_ADVISOR,
    CREATE_ADVISOR,
    UPDATE_ADVISOR,
    DELETE_ADVISOR,
    READ_MASTER,
    READ_LEAD,
    CREATE_LEAD,
    UPDATE_LEAD,
    DELETE_LEAD,
    READ_DOCUMENT,
    READ_LENDER,
    READ_NOTIFICATION,
    CREATE_NOTIFICATION,
    UPDATE_NOTIFICATION,
    READ_OFFICE,
    CREATE_OFFICE,
    READ_STAFF,
    CREATE_STAFF,
    READ_STAGE,
    READ_WORKFLOW,
    READ_TASK,
    UPDATE_TASK,
    READ_USER_PREFERENCES,
    CREATE_USER_PREFERENCES,
    UPDATE_USER_PREFERENCES,
    READ_CAMPAIGN,
    CREATE_CAMPAIGN,
    UPDATE_CAMPAIGN,
    READ_CAMPAIGN_CONFIG
}

