spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}
spring.jpa.properties.hibernate.types.jackson.object.mapper=com.nivasafinance.common.configs.HypersistenceObjectMapperSupplier

# Fix JSONB wrapper issue with Spring Boot 3.5.3 + Hypersistence
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

